version: '3.8'
services:
  frontend:
    image: denuwanthi2k02/accommodationfinder-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://13.232.135.114:5000
    restart: always

  backend:
    image: denuwanthi2k02/accommodationfinder-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://Annex:Annex123@cluster0.abuggtf.mongodb.net/accommodations
      - PORT=5000
      - JWT_SECRET=secret@2025
      - IMAGEKIT_PUBLIC_KEY=public_PCDI5SXMOGsLUcbaWUc7CkP7Sn4=
      - IMAGEKIT_PRIVATE_KEY=private_ro03CB+ycXVmfkC8E7vVdMswzZo=
      - IMAGEKIT_URL_ENDPOINT=https://ik.imagekit.io/tnvc4g4u6
    restart: always