name: Build and Push Docker Images

on:
  push:
    branches:
      - main   # or master depending on your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/accommodationfinder-frontend:latest ./client
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/accommodationfinder-frontend:latest

      - name: Build and push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/accommodationfinder-backend:latest ./server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/accommodationfinder-backend:latest
